/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"
#include "stm32f4xx.h"

void init_gpio(void);

void init_tim3(void);

int main(void)
{
    //Llamar a las funciones de configuración inicial
    init_gpio();

    // Cargamos la configuración del temporizador TIM3 - interrupción cada 0.25 segundos
    init_tim3();

    while (1) {
        
    }

    return 0;
}


void init_gpio(void){
    // RCC->AHB1ENR &= ~(1 << 0); // Deshabilitar el reloj del GPIOA

    // Habilitar el reloj del GPIOA
    RCC->AHB1ENR &= ~RCC_AHB1ENR_GPIOAEN;   // Limpiando la posicion
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;    // Activando la señal

    // Configurar el pin PA5 como salida
    // GPIOA->MODER &= ~(0b11 << (5 * 2))
    GPIOA->MODER &= ~(0b11 << GPIO_MODER_MODE5_Pos); // Limpiando la posicion
    GPIOA->MODER |= (0b01 << GPIO_MODER_MODE5_Pos);  // Configurando como salida

    // Configurar el pin PA5 como push-pull
    GPIOA->OTYPER &= ~GPIO_OTYPER_OT5; // Limpiando y configurando como push-pull

    // Configurar el pin PA5 como velocidad
    GPIOA->OSPEEDR &= ~(0b11 << GPIO_OSPEEDR_OSPEED5_Pos); // Limpiando la posicion
    GPIOA->OSPEEDR |= (0b01 << GPIO_OSPEEDR_OSPEED5_Pos);  // Configurando como velocidad media

    // Configurar el pin PA5 sin pull-up/pull-down
    GPIOA->PUPDR &= ~(0b11 << GPIO_PUPDR_PUPD5_Pos); // LimpiaR, desactiva pull-up/pull-down

    GPIOA->ODR |= (GPIO_ODR_OD5); // Encender el LED (PA5)
}

void init_tim3(){
    //señal de reloj para el TIM3
    RCC->APB1ENR &= ~RCC_APB1ENR_TIM3EN; // Limpiando la posicion
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;  // Activando la señal

    // Configurar el temporizador TIM3
    TIM3->CNT = 0; // Reiniciar el contador
    TIM3->PSC = (16000 - 1); // Divisor por 1600
    TIM3->ARR = (2500 - 1); // Auto-reload para 0.25 segundos

    TIM3->CR1 &= ~( 0X3 << TIM_CR1_CKD_Pos); // Limpiar el bit de habilitación del temporizador
    TIM3->CR1 &= ~(TIM_CR1_ARPE); // Limpiar el bit de habilitación de auto-reload
    TIM3->CR1 |= TIM_CR1_ARPE; // activando el preload 
    TIM3->CR1 &= ~(TIM_CR1_DIR); // Limpiando contador ascendente

    TIM3->DIER |= TIM_DIER_UIE; // Habilitar la interrupción de actualización

    NVIC_EnableIRQ(TIM3_IRQn); // Habilitar la interrupción del TIM3 en el NVIC

    TIM3->CR1 |= TIM_CR1_CEN; // Habilitar el temporizador
}

void TIM3_IRQHandler(void) {
    
    if (TIM3->SR && TIM_SR_UIF) { // Verificar si la bandera esta activa
            TIM3->SR &= ~TIM_SR_UIF; // Limpiar la bandera de interrupción

            // Cambiar el estado del pin PA5 (LED)
            GPIOA->ODR ^= GPIO_ODR_OD5; // Toggle del LED (PA5)
        
    }
}
